config/routes.rb
Rails.application.routes.draw do
  resources :students
  resources :courses_students
  get 'welcome/index'

  resources :courses

  root 'welcome#index'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  get '/enroll' => 'courses#enroll'
  get '/drop' => 'courses#drop'

end

app/models/student.rb
require 'bcrypt'
class Student < ActiveRecord::Base
  validates :first_name, :last_name, presence: true
  validates_uniqueness_of :pennkey
  has_many :courses_student, dependent: :destroy
  has_many :courses, through: :courses_student
  validates :pennkey, presence: true
  validates :password_hash, presence: true

  include BCrypt

  def password
    if self.password_hash != nil
      @password ||= Password.new(password_hash)
    end
  end

  def password=(new_password)
    @password = Password.create(new_password)
    self.password_hash = @password
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  # GET /students
  # GET /students.json
  def index
    if logged_in?
      @students = Student.all
  else 
    redirect_to '/login',  :flash => { :error => "You must login first." }
  end

  end

  # GET /students/1
  # GET /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)
    respond_to do |format|
      if @student.save
        @student.password = student_params[:password]
        session[:student_id] = @student.id
        format.html { redirect_to @student, notice: 'Welcome to PennInTouch' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Your account was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    reset_session
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:first_name, :last_name, :pennkey, :password)
    end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_form.html.erb
<%= form_for(@student) do |f| %>
<p> Sign up for an account with the University of Pennsylvania </p>
  <div id="boxed", class="field">
  <strong>
    <%= f.label :first_name %>:
    <%= f.text_field :first_name %> <br>
    <br>
    <%= f.label :last_name %>:
    <%= f.text_field :last_name %> <br>
    <br>
    <%= f.label :PennKey %>:   
  <%= f.text_field :pennkey %><br>
  <br>
  <%= f.label :password %>:
  <%= f.password_field :password %><br/>
  </strong>
  </div>

  <% if @student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% @student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/students/edit.html.erb
<h1>Editing Student</h1>

<%= render 'form' %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Enrolled Students</h1>

<table>
  <thead>
    <tr>
      <th align="left">Name</th>
      <th align="left">PennKey</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= link_to "#{student.first_name}"+" " + "#{student.last_name}", student %></td>
        <td><%= link_to "#{student.pennkey}", student %></td>
        <td><%= link_to 'Edit', edit_student_path(student) if student == current_student %></td>
        <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } if student == current_student %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/students/new.html.erb
<br>
<header1> <strong>Penn WebLogin</strong></header1>

<%= render 'form' %>

<%= link_to 'Back', students_path %>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @student.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @student.last_name %>
</p>

<p>
  <strong>Pennkey:</strong>
  <%= @student.pennkey %>
</p>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
  <th>Course </th>
  <th>Difficulty (out of 4.0) </th>
    <% @student.courses.each do |course| %>
      <tr>
        <td><%= link_to "#{course.title}", course %></td>
        <td align ="center"><%= course.difficulty %> </td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

<p>
  <strong>Semester Difficulty:</strong>
  <% sum = 0.0 %>
  <% @student.courses.each do |course| %>
  <% sum = course.difficulty.to_f + sum%>
  <% end %>
  <%= 0.0 if sum == 0.0 %>
  <% if sum != 0.0 %>
  <%= sum = sum / @student.courses.count %>
  <% else 0.0 %>
  <% end %>
  <b> <%= "Are you even going to school?" if sum < 3%> </b>
  <c> <%= "You're gonna have a tough semester" if sum >= 3%> </c>
</p>


<%= link_to 'Edit |', edit_student_path(@student) if @student == current_student %>
<%= link_to 'Back', students_path %>