config/routes.rb
Rails.application.routes.draw do
  resources :students
  resources :courses_students
  get 'welcome/index'

  resources :courses

  root 'welcome#index'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  get '/enroll' => 'courses#enroll'
  get '/drop' => 'courses#drop'

end

app/models/courses_student.rb
class CoursesStudent < ActiveRecord::Base
    validates_uniqueness_of :student_id, scope: :course_id
  belongs_to :course
  belongs_to :student
end

app/controllers/courses_students_controller.rb
class CoursesStudentsController < ApplicationController
  before_action :set_courses_student, only: [:show, :edit, :update, :destroy]

  # GET /courses_students
  # GET /courses_students.json
  def index
    @courses_students = CoursesStudent.all
  end

  # GET /courses_students/1
  # GET /courses_students/1.json
  def show
  end

  # GET /courses_students/new
  def new
    @courses_student = CoursesStudent.new
  end

  # GET /courses_students/1/edit
  def edit
  end

  # POST /courses_students
  # POST /courses_students.json
  def create
    @courses_student = CoursesStudent.new(courses_student_params)

    respond_to do |format|
      if @courses_student.save
        format.html { redirect_to @courses_student, notice: 'Courses student was successfully created.' }
        format.json { render :show, status: :created, location: @courses_student }
      else
        format.html { render :new }
        format.json { render json: @courses_student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses_students/1
  # PATCH/PUT /courses_students/1.json
  def update
    respond_to do |format|
      if @courses_student.update(courses_student_params)
        format.html { redirect_to @courses_student, notice: 'Courses student was successfully updated.' }
        format.json { render :show, status: :ok, location: @courses_student }
      else
        format.html { render :edit }
        format.json { render json: @courses_student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses_students/1
  # DELETE /courses_students/1.json
  def destroy
    @courses_student.destroy
    respond_to do |format|
      format.html { redirect_to courses_students_url, notice: 'Courses student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_courses_student
      @courses_student = CoursesStudent.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def courses_student_params
      params.require(:courses_student).permit(:student_id, :course_id)
    end
end

app/helpers/courses_students_helper.rb
module CoursesStudentsHelper
end

app/views/courses_students/_form.html.erb
<%= form_for(@courses_student) do |f| %>
  <% if @courses_student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@courses_student.errors.count, "error") %> prohibited this courses_student from being saved:</h2>

      <ul>
      <% @courses_student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :student_id %><br>
    <%= f.number_field :student_id %>
  </div>
  <div class="field">
    <%= f.label :course_id %><br>
    <%= f.number_field :course_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/courses_students/edit.html.erb
<h1>Editing Courses Student</h1>

<%= render 'form' %>

<%= link_to 'Show', @courses_student %> |
<%= link_to 'Back', courses_students_path %>

app/views/courses_students/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Courses Students</h1>

<table>
  <thead>
    <tr>
      <th>Student</th>
      <th>Course</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @courses_students.each do |courses_student| %>
      <tr>
        <td><%= courses_student.student_id %></td>
        <td><%= courses_student.course_id %></td>
        <td><%= link_to 'Show', courses_student %></td>
        <td><%= link_to 'Edit', edit_courses_student_path(courses_student) %></td>
        <td><%= link_to 'Destroy', courses_student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Courses student', new_courses_student_path %>

app/views/courses_students/new.html.erb
<h1>New Courses Student</h1>

<%= render 'form' %>

<%= link_to 'Back', courses_students_path %>

app/views/courses_students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Student:</strong>
  <%= @courses_student.student_id %>
</p>

<p>
  <strong>Course:</strong>
  <%= @courses_student.course_id %>
</p>

<%= link_to 'Edit', edit_courses_student_path(@courses_student) %> |
<%= link_to 'Back', courses_students_path %>