config/routes.rb
Rails.application.routes.draw do
  resources :students
  resources :courses_students
  get 'welcome/index'

  resources :courses

  root 'welcome#index'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  get '/enroll' => 'courses#enroll'
  get '/drop' => 'courses#drop'

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]

  # GET /courses
  # GET /courses.json
  def index
    if logged_in?
    @courses = Course.all
  else redirect_to '/login',   :flash => { :error => "You must login first." }
  end
   if params[:search]
    @courses = Course.search(params[:search]).order("created_at DESC")
  else
    @courses = Course.all.order("created_at DESC")
  end
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  def enroll
    @course = Course.find(params[:course_id])
    @student = current_student
    @course.students << @student unless @course.students.include?(@student)
    @student.courses << @course unless @student.courses.include?(@course)
    render '/students/show.html.erb'
  end

  def drop
    @course = Course.find(params[:course_id])
    @student = current_student
    @course.students.delete(@student) unless !@course.students.include?(@student)
    @student.courses.delete(@course) unless !@student.courses.include?(@course)
    render '/students/show.html.erb'
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: 'Course was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:title, :description, :difficulty)
    end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_form.html.erb
<%= form_for(@course) do |f| %>
  <% if @course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
      <% @course.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :difficulty %><br>
    <%= f.text_field :difficulty %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/courses/edit.html.erb
<h1>Editing Course</h1>

<%= render 'form' %>

<%= link_to 'Show', @course %> |
<%= link_to 'Back', courses_path %>

app/views/courses/index.html.erb
<body>
<p id="notice"><%= notice %></p>

<h1>Available Courses</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Difficulty</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @courses.each do |course| %>
      <tr>
        <td><%= link_to "#{course.title}", course %></td>
        <td><%= link_to "#{course.description}", course %></td>
        <td align ="center"><%= "#{course.difficulty}"%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if @courses.blank? %>
  <h4>There are no courses containing the term <%= params[:search] %>.</h4>
<% end %>
</body>

app/views/courses/new.html.erb
<h1>New Course</h1>

<%= render 'form' %>

<%= link_to 'Back', courses_path %>

app/views/courses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @course.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @course.description %>
</p>

<p>
  <strong>Difficulty:</strong>
  <%= @course.difficulty %>
</p>
<br>
<% if !@course.students.include?(current_student) %>
<form action="/enroll" method="get">
    <input type="hidden" name="course_id" value= <%= @course.id %> >
    <input type="hidden" name="student_id" value=<%= current_student.id%>>
    <input type="submit" value="Enroll">
</form>
<%end%>
<br>
<% if @course.students.include?(current_student) %>
<form action="/drop" method="get">
    <input type="hidden" name="course_id" value= <%= @course.id %> >
    <input type="hidden" name="student_id" value=<%= current_student.id%>>
    <input type="submit" value="Drop">
</form>
<%end%>
<br>
<%= link_to 'Back', courses_path %>